Tot
5NTeam/iMacDonald pull request #5
Opened 2024-11-26 06:41 UTC by HwangSeokBeom

카드뷰 생성하고 카드뷰 안에 들어갈 이미지뷰, 메뉴이름, 가격 레이블, 추가 버튼 생성했습니다. 각각 작업 단위별로 커밋 했었는데 적용이 안되어서 한번에 요청합니다!ㅠ

2024-11-26 08:01 UTC, taeryu7 approved these changes
주석도 심플하게 잘 달아주시고 좋다고 생각합니다.

struct MenuRepository에서 메뉴 구조체 내부의 항목들은 더 추가하실 예정이신가요?

2024-11-26 08:23 UTC, gyeomsony approved these changes
UI 구성부분 깔끔하네요. 메뉴들은 한글로 변경이 필요할 듯 합니다! 그 외에는 굿굿

2024-11-26 08:27 UTC, Crois0509 requested changes
수정했으면 하는 점이 좀 보이네요~~

2024-11-26 08:27 UTC, Crois0509 commented on iMacDonald/iMacDonald/CardView/MenuData.swift
> +}
케이스 순서 `all, burger, chicken, vegan, side, drink` 순으로 바꿔주세요~

2024-11-26 08:27 UTC, Crois0509 commented on iMacDonald/iMacDonald/CardView/MenuData.swift
> +}
`Codable`은 왜 쓰셨나요??

2024-11-26 08:27 UTC, Crois0509 commented on iMacDonald/iMacDonald/CardView/CardView.swift
> +    static func createCardView(title: String, price: Int, image: UIImage?, category: Categorys) -> UIView {
`static`으로 구현하신 이유가 있나요?

2024-11-26 08:30 UTC, HwangSeokBeom commented on iMacDonald/iMacDonald/CardView/CardView.swift
> +    static func createCardView(title: String, price: Int, image: UIImage?, category: Categorys) -> UIView {
다른 뷰에서 인스턴스 생성 없이 사용하시라고 static으로 만들었습니다!

2024-11-26 08:35 UTC, HwangSeokBeom commented on iMacDonald/iMacDonald/CardView/MenuData.swift
> +}
순서 변경하고 Codable 삭제 했습니다. 쓴 이유 없습니다.. 복붙하다가 딸려 들어갔습니다.

2024-11-26 08:35 UTC, gyeomsony commented on iMacDonald/iMacDonald/CardView/CardView.swift
> +    static func createCardView(title: String, price: Int, image: UIImage?, category: Categorys) -> UIView {
오 저도 궁금해요

2024-11-26 08:38 UTC, HwangSeokBeom commented
> UI 구성부분 깔끔하네요. 메뉴들은 한글로 변경이 필요할 듯 합니다! 그 외에는 굿굿

메뉴 이름 한글로 되어 있지 않나여??

2024-11-26 09:00 UTC, jeongmuya approved these changes

2024-11-26 09:00 UTC, jeongmuya commented on iMacDonald/iMacDonald/CardView/MenuData.swift
👏 코드가 매우 깔끔하고 가독성이 뛰어납니다!

2024-11-27 02:42 UTC, gyeomsony approved these changes

2024-11-27 02:50 UTC, Crois0509 approved these changes
몇 가지 수정할 부분이 있지만 전체적인 코드는 문제 없다고 생각합니다!!
수고하셨습니다~~

2024-11-27 02:50 UTC, Crois0509 commented on iMacDonald/iMacDonald/CardView/MenuData.swift
> +}
이 구조체를 별도로 선언한 이유가 있나요?
내부에 `menuList`라는 인스턴스 하나만 가진다면 위에 `MenuData` 안에 구현했어도 문제 없었을 것 같다고 생각해요!

2024-11-27 02:50 UTC, Crois0509 commented on iMacDonald/iMacDonald/CardView/CardViewController.swift
> +            make.height.equalTo(cardView.snp.width).multipliedBy(1.2) // 카드뷰의 높이를 너비의 1.2배로 설정
비율로 설정하는거 아주 좋아요

2024-11-27 02:50 UTC, Crois0509 commented on iMacDonald/iMacDonald/CardView/CardView.swift
> +    }
메소드의 역할분리가 잘 되어있는 것 같네요

2024-11-27 02:50 UTC, Crois0509 commented on iMacDonald/iMacDonald/CardView/CardView.swift
> +        self.backgroundColor = .white
카드 색을 white로 하면 다크모드에서도 흰색으로 보여요!!
이럴 때는 systembackground 컬러를 사용하거나, 저희가 에셋에서 적용한 컬러 중에서 적당한 걸 선택하는게 좋습니다

2024-11-27 02:50 UTC, Crois0509 commented on iMacDonald/iMacDonald/CardView/CardView.swift
> +        nameLabel.textColor = .black
여기도 텍스트 컬러를 black으로 해두면 다크모드에서 글씨가 안 보이게 되니 수정이 필요하겠네요

2024-11-27 02:50 UTC, Crois0509 commented on iMacDonald/iMacDonald/CardView/CardView.swift
> +        priceLabel.textColor = .darkGray
여기도 색 변경 하셔야겠죠??

2024-11-27 04:17 UTC, gyeomsony commented on iMacDonald/iMacDonald/CardView/CardView.swift
> +        nameLabel.textColor = .black
이렇게 섬세한 코드리뷰들을 보니까 너무 좋네요 ,, 햐

2024-11-27 04:27 UTC, merged